Multiple advancements
* Finish Bash scripts (based mostly on redirecting stdin-stdout)
* Write the main function (partial) (based mostly on stdin-stdout style)
* Write helper functions to main (partial: inserer, suppression)
* Add JSON serializing and deserializing functions for the Hybrid Trie using cJSON
* Rename Hybrid Trie functions to avoid name clashes further down the road

diff --git a/fusion b/fusion
--- a/fusion
+++ b/fusion
@@ -1,3 +1,28 @@
 #!/usr/bin/env bash
 
-echo $0
+# Check if exactly two arguments are provided
+if [ "$#" -ne 3 ]; then
+    echo "Usage: $0 <x> <y> <z>"
+    echo "x: 0 -> Patricia-Trie | 1 -> Hybrid Trie"
+    echo "y: A JSON file representing a trie tree"
+    echo "z: A JSON file representing a trie tree"
+    exit 1
+fi
+
+x=$1
+y=$2
+z=$3
+
+# Check if x is either 0 or 1
+if [ "$x" -eq 0 ]; then
+    outfile="pat.json"
+elif [ "$x" -eq 1 ]; then
+    outfile="trie.json"
+else
+    echo "Error: x must be 0 or 1"
+    echo "x: 0 -> Patricia-Trie | 1 -> Hybrid Trie"
+    exit 1
+fi
+
+# Run the program
+./tries 2 "$x" "$y" "$z" >"$outfile"
diff --git a/profondeurMoyenne b/profondeurMoyenne
--- a/profondeurMoyenne
+++ b/profondeurMoyenne
@@ -1,3 +1,23 @@
 #!/usr/bin/env bash
 
-echo $0
+# Check if exactly two arguments are provided
+if [ "$#" -ne 2 ]; then
+    echo "Usage: $0 <x> <y>"
+    echo "x: 0 -> Patricia-Trie | 1 -> Hybrid Trie"
+    echo "y: A JSON file representing a trie tree"
+    exit 1
+fi
+
+x=$1
+y=$2
+outfile="profondeur.txt"
+
+# Check if x is either 0 or 1
+if ! [ "$x" -eq 0 -o "$x" -eq 1 ]; then
+    echo "Error: x must be 0 or 1"
+    echo "x: 0 -> Patricia-Trie | 1 -> Hybrid Trie"
+    exit 1
+fi
+
+# Run the program
+./tries 4 "$x" <"$y" >"$outfile"
diff --git a/suppression b/suppression
--- a/suppression
+++ b/suppression
@@ -1,3 +1,26 @@
 #!/usr/bin/env bash
 
-echo $0
+# Check if exactly two arguments are provided
+if [ "$#" -ne 2 ]; then
+    echo "Usage: $0 <x> <y>"
+    echo "x: 0 -> Patricia-Trie | 1 -> Hybrid Trie"
+    echo "y: A text file with one word per line"
+    exit 1
+fi
+
+x=$1
+y=$2
+
+# Check if x is either 0 or 1
+if [ "$x" -eq 0 ]; then
+    inoutfile="pat.json"
+elif [ "$x" -eq 1 ]; then
+    inoutfile="trie.json"
+else
+    echo "Error: x must be 0 or 1"
+    echo "x: 0 -> Patricia-Trie | 1 -> Hybrid Trie"
+    exit 1
+fi
+
+# Run the program
+./tries 1 "$x" "$inoutfile" <"$y"
